version: "3"
services:
  server:
    image: atmtrxproduct
    ports:
      - "9084:9084"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/db_atm?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=db_atm

networks:
  springmysql-net: